# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Why sleep is the best thing ever
email: kane.foreman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
      Sleep is amazing, but most people are in denial. Learn why your favorite thing should be sleep
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tehteribalsepeler.github.io" # the base hostname & protocol for your site
twitter_username: kanejupiter
github_username:  TehTeribalSepeler

# Build settings
markdown: kramdown
